### ISSUE TITLE
Not showing footer items

### ISSUE THREAD

**Issue by fatiherdogan01** [Teknasyon-Teknoloji/deepwall-react-native-sdk#37]
Hi,

**Version**
deepwall-react-native-sdk: 3.0.0

**Description**
I'm not seeing footer items (Privacy Policy, Restore etc.) in real device.

Real Device             |  Dashboard Paywall
:-------------------------:|:-------------------------:
<img width="153" alt="Ekran Resmi 2022-07-25 09 24 44" src="https://user-images.githubusercontent.com/13077861/180715088-c233c0de-8707-4beb-80bf-fd6889bf31b3.png">|  <img width="153" alt="Ekran Resmi 2022-07-25 09 23 38" src="https://user-images.githubusercontent.com/13077861/180715072-4b7a71eb-bf31-4abf-b8b2-a19e66d1f1a1.png">

Have you any information or solution?

Thanks.

**Comment by semiherdogan** [comment]
Hi,
This issue is related to theme upgrade. 
Please write to support for upgrading this theme.
Let us know if issue persist after theme upgrade.
