### ISSUE TITLE
Paywall won't open [IOS]

### ISSUE THREAD

**Issue by MCElmo** [Teknasyon-Teknoloji/deepwall-react-native-sdk#38]
I've been trying for a while to connect DeepWall to React Native but have been unsuccessful. I even tried removing react native navigation but even the example code doesn't seem to work for me.

I keep getting no response from DeepWall: 

OG  deepWallPaywallRequested
 LOG  {}
 LOG  deepWallPaywallResponseReceived
 LOG  {}

Additionally in my Xcode console I see: [native] Unrecognized font family 'DefaultFont' logged a bunch of time.

**Comment by semiherdogan** [comment]
Hi, 
Seems like sdk works but view side has some issues,
Can you write your project's dependencies with versions like below:
react native: 0.63.0
deepwall sdk: 3.0.0
...

**Comment by semiherdogan** [comment]
Hi,
It looks like there hasn't been a reply in 30 days, so I'm closing this issue.
Please let us know if issue persist.
